/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans:    ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      colors: {
        bg:       'var(--color-bg)',
        surface:  'var(--color-surface)',
        'surface-2': 'var(--color-surface-2)',
        border:   { DEFAULT: 'var(--color-border)', light: 'var(--color-border-light)' },
        primary:  { DEFAULT: 'var(--color-primary)', glow: 'var(--color-primary-glow)' },
        secondary:'var(--color-secondary)',
        cyan:     'var(--color-cyan)',
        emerald:  'var(--color-emerald)',
        gold:     'var(--color-gold)',
        coral:    'var(--color-coral)',
        heading:  'var(--color-heading)',
        text:     'var(--color-text)',
        muted:    'var(--color-muted)',
        subtle:   'var(--color-subtle)',
        /* Legacy compat */
        background: 'var(--color-background)',
        card:     'var(--color-card)',
        body:     'var(--color-body)',
        ink:      'var(--color-ink)',
        charcoal: 'var(--color-charcoal)',
        bone:     'var(--color-bone)',
        violet:   'var(--color-violet)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #6C63FF 0%, #00D4FF 100%)',
        'gradient-secondary': 'linear-gradient(135deg, #FF6584 0%, #F59E0B 100%)',
        'gradient-cta':    'linear-gradient(135deg, #6C63FF 0%, #00D4FF 100%)',
        'gradient-hero':   'radial-gradient(ellipse 80% 80% at 50% -20%, rgba(108,99,255,0.15) 0%, transparent 60%)',
        'gradient-card':   'linear-gradient(135deg, rgba(108,99,255,0.06) 0%, rgba(13,13,26,0.8) 50%, rgba(0,212,255,0.03) 100%)',
        'gradient-mesh':   'radial-gradient(ellipse 60% 50% at 10% 40%, rgba(108,99,255,0.08) 0%, transparent 70%), radial-gradient(ellipse 50% 60% at 90% 60%, rgba(0,212,255,0.05) 0%, transparent 70%)',
      },
      boxShadow: {
        'glow-sm':     '0 0 12px rgba(108, 99, 255, 0.3)',
        'glow':        '0 0 24px rgba(108, 99, 255, 0.4), 0 0 60px rgba(108, 99, 255, 0.15)',
        'glow-lg':     '0 0 40px rgba(108, 99, 255, 0.5), 0 0 120px rgba(108, 99, 255, 0.2)',
        'glow-cyan':   '0 0 24px rgba(0, 212, 255, 0.4)',
        'glow-secondary': '0 0 24px rgba(255, 101, 132, 0.4)',
        'glow-gold':   '0 0 24px rgba(245, 158, 11, 0.4)',
        'glow-accent': '0 0 20px rgba(108, 99, 255, 0.35)',
        'card':        '0 4px 24px -4px rgba(0, 0, 0, 0.4)',
        'card-hover':  '0 24px 80px -12px rgba(108, 99, 255, 0.2)',
        'glass':       '0 8px 32px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255,255,255,0.06)',
        'soft':        '0 4px 20px -2px rgba(0,0,0,0.2)',
        'soft-lg':     '0 10px 40px -5px rgba(0,0,0,0.3)',
        'soft-xl':     '0 20px 60px -8px rgba(0,0,0,0.4)',
      },
      animation: {
        'fade-in':        'fadeIn 0.6s ease-out forwards',
        'slide-up':       'slideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-down':     'slideDown 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in':       'scaleIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'float':          'float 6s ease-in-out infinite',
        'float-slow':     'floatSlow 8s ease-in-out infinite',
        'pulse-glow':     'pulseGlow 3s ease-in-out infinite',
        'spin-slow':      'spin 8s linear infinite',
        'shimmer':        'shimmer 2.5s linear infinite',
        'border-flow':    'borderFlow 4s linear infinite',
      },
      keyframes: {
        fadeIn:      { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp:     { '0%': { transform: 'translateY(24px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown:   { '0%': { transform: 'translateY(-16px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        scaleIn:     { '0%': { transform: 'scale(0.9)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        float:       { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        floatSlow:   { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-20px)' } },
        pulseGlow:   { '0%,100%': { opacity: '0.5', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.05)' } },
        shimmer:     { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        borderFlow:  { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'bounce-in': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}
